FROM php:8.3-fpm-alpine

RUN apk add --no-cache \
    icu-dev \
    oniguruma-dev \
    libzip-dev \
    mysql-client \
    bash \
    curl

RUN docker-php-ext-install \
    pdo_mysql \
    mbstring \
    intl \
    zip \
    pcntl

WORKDIR /var/www/html
