FROM php:8.3-fpm-alpine

# Base dependencies
RUN apk add --no-cache \
    icu-dev \
    oniguruma-dev \
    libzip-dev \
    mysql-client \
    bash \
    git \
    curl \
    unzip

RUN docker-php-ext-install \
    pdo_mysql \
    mbstring \
    intl \
    zip \
    pcntl

# Composer
RUN curl -sS https://getcomposer.org/installer | php -- \
    --install-dir=/usr/bin \
    --filename=composer

# COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

COPY docker/php/opcache.ini /usr/local/etc/php/conf.d/opcache.ini
