<?php

namespace App\Livewire\Mobile;

use Livewire\Component;
use App\Models\Mould;
use App\Models\Machine;

class Scanner extends Component
{
    public $search = '';
    public $activeTab = 'scan'; // 'scan' or 'manual'
    
    public function handleScan($code)
    {
        // Support full URLs generated by MouldQrBatch (e.g. http://domain.com/moulds/uuid)
        if (str_contains($code, '/moulds/')) {
            $parts = explode('/moulds/', $code);
            $id = end($parts);
            // remove any query strings if present
            $id = explode('?', $id)[0];
            $mould = Mould::find($id);
            if ($mould) {
                return redirect()->route('mobile.mould-detail', $mould);
            }
        }
        
        // Future proofing for machines URL if we add it
        if (str_contains($code, '/machines/')) {
            $parts = explode('/machines/', $code);
            $id = end($parts);
            $id = explode('?', $id)[0];
            $machine = Machine::find($id);
            if ($machine) {
                return redirect()->route('mobile.jobs', ['machine' => $id]);
            }
        }

        if (str_starts_with($code, 'MACHINE:')) {
            $id = str_replace('MACHINE:', '', $code);
            $machine = Machine::find($id);
            if ($machine) {
                return redirect()->route('mobile.jobs', ['machine' => $id]);
            }
            $this->dispatch('scan-error', message: 'Machine not found: ' . $code);
            return;
        }

        // Expected format: MOULD:uuid or just uuid? 
        $id = str_replace('MOULD:', '', $code);
        $mould = Mould::find($id);

        if ($mould) {
            return redirect()->route('mobile.mould-detail', $mould);
        }

        // If not found, dispatch error
        $this->dispatch('scan-error', message: 'QR Code not recognized or item not found.');
    }

    public function selectMould($id)
    {
        $mould = Mould::find($id);
        if ($mould) {
            return redirect()->route('mobile.mould-detail', $mould);
        }
    }

    public function selectMachine($id)
    {
        $machine = Machine::find($id);
        if ($machine) {
            return redirect()->route('mobile.jobs', ['machine' => $id]);
        }
    }

    public function render()
    {
        $moulds = collect();
        $machines = collect();

        if (strlen($this->search) >= 2) {
            $moulds = Mould::where(function($q) {
                $q->where('code', 'like', '%' . $this->search . '%')
                  ->orWhere('name', 'like', '%' . $this->search . '%')
                  ->orWhereHas('parts', function ($query) {
                      $query->where('part_number', 'like', '%' . $this->search . '%')
                            ->orWhere('part_name', 'like', '%' . $this->search . '%');
                  });
            })->limit(5)->get();
            
            $machines = Machine::where(function($q) {
                $q->where('code', 'like', '%' . $this->search . '%')
                  ->orWhere('name', 'like', '%' . $this->search . '%');
            })->limit(5)->get();
        }

        return view('livewire.mobile.scanner', [
            'mouldResults' => $moulds,
            'machineResults' => $machines,
        ])->layout('layouts.mobile');
    }
}
